name: manual_workflow
on: workflow_dispatch
  inputs:
    environment: 
      default: "dev"
      required: false
      type: string
    version: 
      required: true
      type: string
jobs:
  manual_workflow_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: print step
        run: |
          echo "Environment: {{ inputs.environment }}"
          echo "Version: {{ inputs.version }}"

